=== dbdipview/dbdipview/packager/list.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.0">
	<xs:element name="revision">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="xs:date" name="date"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="revisions">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="revision" maxOccurs="unbounded" minOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="comment" type="xs:string"/>

	<xs:element name="schema" type="xs:string"/>

	<xs:element name="schemas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="schema" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="view" type="xs:string"/>

	<xs:element name="views">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="view" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="table">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute type="xs:string" name="file" use="optional"/>
					<xs:attribute type="xs:string" name="format" use="optional"/>
					<xs:attribute type="xs:string" name="date_format" use="optional"/>
					<xs:attribute type="xs:string" name="delimiter" use="optional"/>
					<xs:attribute type="xs:string" name="encoding" use="optional"/>
					<xs:attribute type="xs:string" name="header" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="tables">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="table" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="bfile" type="xs:string"/>

	<xs:element name="bfiles">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="bfile" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="revisions"/>
				<xs:element ref="comment"/>
				<xs:element ref="schemas" minOccurs="0" maxOccurs="1" />
				<xs:element ref="views"   minOccurs="0" maxOccurs="1" />
				<xs:element ref="tables"  minOccurs="0" maxOccurs="1" />
				<xs:element ref="bfiles"  minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute type="xs:byte" name="schemaMajorVersion"/>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== dbdipview/dbdipview/tools/template/metadata/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="list.xsd" schemaMajorVersion="1">
	<revisions>
		<revision date="2024-10-11">Template. Change the values.</revision>
	</revisions>
	<comment>
This is the main configuration file for deployment of a dbDIPview package.
Describes the objects that need some action during deployment or later removal.
Use the following elements (to enable setting the permission or loading the files):
- For CSV based packages: SCHEMA, TABLE, BFILES
- For SIARD based packages: SCHEMA
- For additional VIEW or TABLE elements created by createdb01.sql: VIEW
See TestAndDemo for examples.
	</comment>
	<schemas>
		<!-- as used in SIARD and query.xml; needed here to set permission  -->
		<schema>schemaName</schema>
	</schemas>
	<views>
		<!-- views are usually created by createddb01.sql; needed here to set permission -->
		<view></view>
	</views>
	<tables>
		<!-- see packager list.xsd for all attributes and their default values;
			CSV come from EXT DDV or external package as defined in order file -->
		<table file="fileName.csv">schemaName.tableName</table>
	</tables>
	<bfiles>
		<!-- .zip, .tar, .tar.gz packages in EXT DDV packages with LOB files -->
		<bfile></bfile>
	</bfiles>
</configuration>

=== dbdipview/dbdipview/testing/TestAndDemo4/metadata/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="list.xsd" schemaMajorVersion="1">
	<revisions>
		<revision date="2022-11-13">Migration from list.txt to list.xml</revision>
		<revision date="2024-09-23">External AIP package with CSV files</revision>
	</revisions>
	<comment>TestAndDemo4 - dbDIPview regression testMake sure that the 
    tables are created beforehand from a SIARD file! The table is loaded from two CSV files that are in a separate package.</comment>
	<schemas>
		<schema>HR members</schema>
	</schemas>
	<tables>
		<table file="HRemployees.csv" header="0">HR members.HR employees</table>
		<table file="HRemployeesPart2.csv" header="0">HR members.HR employees</table>
	</tables>
</configuration>

=== dbdipview/dbdipview/testing/TestAndDemo2/metadata/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="list.xsd" schemaMajorVersion="1">
	<revisions>
		<revision date="2022-11-13">Migration from list.txt to list.xml</revision>
		<revision date="2023-02-23">Added nullas</revision>
		<revision date="2023-08-16">Added models_full_text_view</revision>
	</revisions>
	<comment>TestAndDemo2 - dbDIPview regression test</comment>
	<schemas>
		<schema>AirplanesLinks</schema>
		<schema>TestCSV</schema>
		<schema>views</schema>
	</schemas>
	<views>
		<view>AirplanesLinks.view_codes_NumOfEngines</view>
		<view>views.my_view</view>
		<view>views.models_full_text_view</view>
	</views>
	<tables>
		<table file="models.csv">AirplanesLinks.models</table>
		<table file="Keys semicolon.csv"        delimiter=";">TestCSV.test1</table>
		<table file="Keys comma.csv"                            header="0">TestCSV.TEST2</table>
		<table file="Keys tab.csv"              delimiter="tab" header="0">TestCSV.test3</table>
		<table file="Keys tab.txt" format="TSV" delimiter="tab" header="0" nullas="NULL">"TestCSV"."test4"</table>
	</tables>
	<bfiles>
		<!-- these files are in EXT DDV package -->
		<bfile>filesInTar.tar</bfile>
		<bfile>filesInTarGz.tar.gz</bfile>
		<bfile>filesInTgz.tgz</bfile>
		<!-- this file is in an external package -->
		<bfile>filesInZip.zip</bfile>
	</bfiles>
</configuration>

=== dbdipview/dbdipview/testing/TestAndDemo5/metadata/list.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="list.xsd" schemaMajorVersion="1">
	<revisions>
		<revision date="2022-11-13">Migration from list.txt to list.xml</revision>
		<revision date="2025-02-21">views</revision>
	</revisions>
	<comment>TestAndDemo5 - dbDIPview regression test
  Two VIEWS and no SCHEMA and TABLE in this packageUse with TestAndDemo4.siard (database) 
  and TestAndDemo4.tar.gz (EXT DDV with a CSV table data) and TestAndDemo5.zip (VIEWs, viewer)
  See order_TestAndDemo5.xml</comment>
	<schemas>
		<schema>views</schema>
	</schemas>
	<views>
		<view>views.my_test_viewA</view>
		<view>"views"."my_test_viewB"</view>
	</views>
</configuration>
